/// A top-level key in debcargo.toml.
pub struct TopLevelKey {
    pub name: &'static str,
    pub description: &'static str,
    pub value_type: TopLevelValueType,
}

pub enum TopLevelValueType {
    Bool,
    String,
    StringArray,
}

/// Keys valid at the [source] table level.
pub struct SourceKey {
    pub name: &'static str,
    pub description: &'static str,
    pub value_type: SourceValueType,
}

pub enum SourceValueType {
    String,
    StringArray,
    Bool,
}

/// Keys valid in [packages.KEY] tables.
pub struct PackageKey {
    pub name: &'static str,
    pub description: &'static str,
    pub value_type: PackageValueType,
}

pub enum PackageValueType {
    Bool,
    String,
    StringArray,
}

pub static TOP_LEVEL_KEYS: &[TopLevelKey] = &[
    TopLevelKey {
        name: "bin",
        description: "Whether to generate a package for the binary crate (default: true unless semver_suffix is true)",
        value_type: TopLevelValueType::Bool,
    },
    TopLevelKey {
        name: "bin_name",
        description: "Name for the binary crate package",
        value_type: TopLevelValueType::String,
    },
    TopLevelKey {
        name: "lib",
        description: "Whether to generate a package for the library crate (default: true)",
        value_type: TopLevelValueType::Bool,
    },
    TopLevelKey {
        name: "semver_suffix",
        description: "Add the semver to the package name to allow co-installation with other versions",
        value_type: TopLevelValueType::Bool,
    },
    TopLevelKey {
        name: "overlay",
        description: "Overlay directory to copy on top of the generated one, relative to this file",
        value_type: TopLevelValueType::String,
    },
    TopLevelKey {
        name: "crate_src_path",
        description: "Local directory where crate can be found, instead of crates.io",
        value_type: TopLevelValueType::String,
    },
    TopLevelKey {
        name: "excludes",
        description: "Paths from the crate tarball to exclude from the orig tarball (glob syntax)",
        value_type: TopLevelValueType::StringArray,
    },
    TopLevelKey {
        name: "whitelist",
        description: "Paths manually reviewed to adhere to Debian policy (suppresses false-positive errors)",
        value_type: TopLevelValueType::StringArray,
    },
    TopLevelKey {
        name: "repack_suffix",
        description: "Suffix added to upstream version when the tarball is repacked (default: \"+dfsg\" if excludes are set)",
        value_type: TopLevelValueType::String,
    },
    TopLevelKey {
        name: "allow_prerelease_deps",
        description: "Allow prerelease deps by rewriting them to the released version",
        value_type: TopLevelValueType::Bool,
    },
    TopLevelKey {
        name: "summary",
        description: "Stem of the short description for each binary package",
        value_type: TopLevelValueType::String,
    },
    TopLevelKey {
        name: "description",
        description: "Stem of the long description for each binary package",
        value_type: TopLevelValueType::String,
    },
    TopLevelKey {
        name: "maintainer",
        description: "Maintainer field (defaults to pkg-rust-team)",
        value_type: TopLevelValueType::String,
    },
    TopLevelKey {
        name: "uploaders",
        description: "Uploaders for the package (affects Uploaders: field and debian/copyright)",
        value_type: TopLevelValueType::StringArray,
    },
    TopLevelKey {
        name: "collapse_features",
        description: "Force all crate features into a single feature (should not be enabled unless absolutely necessary)",
        value_type: TopLevelValueType::Bool,
    },
    TopLevelKey {
        name: "requires_root",
        description: "Value for the Rules-Requires-Root field in debian/control",
        value_type: TopLevelValueType::String,
    },
];

pub static SOURCE_KEYS: &[SourceKey] = &[
    SourceKey {
        name: "policy",
        description: "Debian Standards-Version to use",
        value_type: SourceValueType::String,
    },
    SourceKey {
        name: "homepage",
        description: "Override or provide missing homepage for crate",
        value_type: SourceValueType::String,
    },
    SourceKey {
        name: "vcs_git",
        description: "Override the Vcs-Git entry",
        value_type: SourceValueType::String,
    },
    SourceKey {
        name: "vcs_browser",
        description: "Override the Vcs-Browser entry",
        value_type: SourceValueType::String,
    },
    SourceKey {
        name: "section",
        description: "Section override for the source package",
        value_type: SourceValueType::String,
    },
    SourceKey {
        name: "build_depends",
        description: "Extra Build-Depends on top of those generated by debcargo",
        value_type: SourceValueType::StringArray,
    },
    SourceKey {
        name: "build_depends_arch",
        description: "Extra Build-Depends-Arch on top of those generated by debcargo",
        value_type: SourceValueType::StringArray,
    },
    SourceKey {
        name: "build_depends_indep",
        description: "Extra Build-Depends-Indep on top of those generated by debcargo",
        value_type: SourceValueType::StringArray,
    },
    SourceKey {
        name: "build_depends_excludes",
        description: "Build-Depends to subtract from those generated by debcargo (to break cycles)",
        value_type: SourceValueType::StringArray,
    },
    SourceKey {
        name: "skip_nocheck",
        description: "If true, do not add <!nocheck> annotations to build dependencies",
        value_type: SourceValueType::Bool,
    },
];

pub static PACKAGE_KEYS: &[PackageKey] = &[
    PackageKey {
        name: "section",
        description: "Section override for the binary package",
        value_type: PackageValueType::String,
    },
    PackageKey {
        name: "summary",
        description: "Short description for the package",
        value_type: PackageValueType::String,
    },
    PackageKey {
        name: "description",
        description: "Long description for the package",
        value_type: PackageValueType::String,
    },
    PackageKey {
        name: "architecture",
        description: "Value for the Architecture field of the package",
        value_type: PackageValueType::StringArray,
    },
    PackageKey {
        name: "multi_arch",
        description: "Value for the Multi-Arch field (no|same|foreign|allowed)",
        value_type: PackageValueType::String,
    },
    PackageKey {
        name: "depends",
        description: "Additional Depends on top of those generated by debcargo",
        value_type: PackageValueType::StringArray,
    },
    PackageKey {
        name: "test_is_broken",
        description: "Mark the autopkgtest as broken/flaky to ignore failures",
        value_type: PackageValueType::Bool,
    },
    PackageKey {
        name: "test_depends",
        description: "Extra system tools or libraries needed for autopkgtest",
        value_type: PackageValueType::StringArray,
    },
    PackageKey {
        name: "test_architecture",
        description: "Architecture restrictions (positive or negative) for autopkgtests",
        value_type: PackageValueType::StringArray,
    },
    PackageKey {
        name: "recommends",
        description: "Additional Recommends for the package",
        value_type: PackageValueType::StringArray,
    },
    PackageKey {
        name: "suggests",
        description: "Additional Suggests for the package",
        value_type: PackageValueType::StringArray,
    },
    PackageKey {
        name: "provides",
        description: "Additional Provides for the package",
        value_type: PackageValueType::StringArray,
    },
    PackageKey {
        name: "breaks",
        description: "Breaks relationships for the package",
        value_type: PackageValueType::StringArray,
    },
    PackageKey {
        name: "replaces",
        description: "Replaces relationships for the package",
        value_type: PackageValueType::StringArray,
    },
    PackageKey {
        name: "conflicts",
        description: "Conflicts relationships for the package",
        value_type: PackageValueType::StringArray,
    },
    PackageKey {
        name: "extra_lines",
        description: "Extra lines to include in the stanza (freeform)",
        value_type: PackageValueType::StringArray,
    },
];

pub static MULTI_ARCH_VALUES: &[(&str, &str)] = &[
    (
        "no",
        "Package cannot be co-installed with itself from a foreign architecture",
    ),
    (
        "same",
        "Package can be co-installed with itself (e.g. development files)",
    ),
    (
        "foreign",
        "Package can satisfy dependencies from a foreign architecture",
    ),
    ("allowed", "Co-installation allowed but not required"),
];

/// Description of a top-level debcargo.toml key, if known.
pub fn top_level_key_description(name: &str) -> Option<&'static str> {
    TOP_LEVEL_KEYS
        .iter()
        .find(|k| k.name == name)
        .map(|k| k.description)
}

/// Description of a `[source]` table key, if known.
pub fn source_key_description(name: &str) -> Option<&'static str> {
    SOURCE_KEYS
        .iter()
        .find(|k| k.name == name)
        .map(|k| k.description)
}

/// Description of a `[packages.*]` table key, if known.
pub fn package_key_description(name: &str) -> Option<&'static str> {
    PACKAGE_KEYS
        .iter()
        .find(|k| k.name == name)
        .map(|k| k.description)
}
