[package]
name = "debian-lsp"
version = "0.1.1"
edition = "2021"
authors = ["Jelmer Vernooĳ <jelmer@debian.org>"]
description = "Language Server Protocol implementation for Debian control files with field completion, diagnostics, and quickfixes"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jelmer/debian-lsp"
keywords = ["lsp", "debian", "control", "language-server"]
categories = ["development-tools", "text-editors"]

[dependencies]
# debian-analyzer = "0.159.0"
debian-control = "0.1.47"
tower-lsp = "0.20"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
salsa = "0.23"
text-size = "1.1"

[dev-dependencies]
tower-lsp-macros = "0.9"
tokio-test = "0.4"
tower = "0.5"
tower-service = "0.3"

[[bin]]
name = "debian-lsp"
test = true
